### PR TITLE
changes ofxgo.Client to ofxgo.BasicClient

### PR DESCRIPTION
**Pull request by abates**
Updates code to accomodate https://github.com/aclindsa/ofxgo/commit/94a77ac754d1a2e2ae8d10d07b7f15d471230701

### CODE REVIEW

**Comment by aclindsa** [comment]
Thanks! I think you'll need to also update the dependency files to point to the latest ofxgo to allow the CI build to pass (one reason I didn't rush to update this code when I changed the ofxgo API). I _**do**_ want to move to modules instead of dep, but haven't gotten around to that yet...

**Comment by abates** [comment]
My mistake, I didn't even notice that dep is being used.  I followed the build/install instructions and my build failed so thats why I went hunting.  I can update the dependency if you want, or we can just close the PR.  Let me know what you'd like to do.

**Comment by aclindsa** [comment]
Doh, that's poor on my part for having build/install instructions that don't use the same method I'm using for my CI :stuck_out_tongue:

I'll gladly merge this once the dep dependency stuff is updated. I suspect that's probably better than just closing it since then the instructions in the README won't be broken.

**Comment by abates** [comment]
Okay, I've updated the dependencies and travis is now happy.

**Comment by aclindsa** [comment]
Thanks, @abates !

**Pull request merged**
